# Generated by Django 3.1 on 2020-08-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('livello', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.CharField(max_length=200)),
                ('mese', models.CharField(max_length=200)),
                ('anno', models.CharField(max_length=200)),
            ],
        ),
    ]
