# Generated by Django 3.1 on 2020-08-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orariuscitesettimanali', models.CharField(max_length=200)),
                ('giorniuscitesettimanali', models.IntegerField(blank=True, null=True)),
                ('numeropartecipantiperturno', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clienti',
            old_name='age',
            new_name='eta',
        ),
        migrations.RemoveField(
            model_name='clienti',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clienti',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clienti',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prenotazioni',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='prenotazioni',
            name='mese',
        ),
        migrations.AddField(
            model_name='clienti',
            name='autorizzato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienti',
            name='facebook',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienti',
            name='google',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienti',
            name='indirizzo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienti',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenotazioni',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prenotazioni.clienti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenotazioni',
            name='note',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenotazioni',
            name='ora',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienti',
            name='cognome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='email',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='password',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='prenotazioni',
            name='giorno',
            field=models.CharField(max_length=50),
        ),
    ]
