# Generated by Django 3.1 on 2020-08-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0002_auto_20200818_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienti',
            name='autorizzato',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='cognome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='facebook',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='google',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='indirizzo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='livello',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='password',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='telefono',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prenotazioni',
            name='giorno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prenotazioni',
            name='note',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='prenotazioni',
            name='ora',
            field=models.CharField(default='', max_length=50),
        ),
    ]
