# Generated by Django 3.1 on 2020-08-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0004_auto_20200818_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazioni',
            name='accettata',
            field=models.IntegerField(default=0),
        ),
    ]
